services:
  timescale:
    container_name: timescale
    image: timescale/timescaledb:2.19.3-pg14
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer:5.3.0
    restart: always
    ports:
      - 8080:8080
