{
 "title": "Generic Preview",
 "tags": [ "General" ],
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  { "title": "Γενικές πληροφορίες", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Greece Devices Overview",
   "type": "table",
   "description": "Export functionality for data by tapping on the panel \"Greece Devices Overview\"\n  `triple dot` -> `inspect` -> `Data` -> `Data options`. \n  Download the file by checking all boxes and pressing the download button.\n ",
   "gridPos": { "h": 17, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (de.id_collar)\r\n  ei.farm_area, ei.farm_nomos,\r\n  de.id_collar, d.animal_type, de.created_at\r\nFROM device_data de\r\nJOIN devices d ON de.id_collar = d.id\r\nLEFT JOIN users ei ON d.id_user = ei.id\r\nWHERE $__timeFilter(created_at)\r\nORDER BY de.id_collar, de.created_at DESC;\r\n"
    },
    {
     "rawSql": "SELECT\r\n  id_collar,\r\n  MIN(min_temperature) AS min_temperature,\r\n  AVG(avg_temperature) AS avg_temperature,\r\n  MAX(max_temperature) AS max_temperature,\r\n  COUNT(*)\r\nFROM device_data_daily_agg\r\nWHERE $__timeFilter(day)\r\nGROUP BY id_collar;\r\n"
    }
   ]
  },
  {
   "title": "Greece - Active Devices Past 7 Days",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (de.id_collar)\r\n  de.id_collar, de.created_at, de.longitude, de.latitude,\r\n  d.animal_type,\r\n  ei.farm_area, ei.farm_nomos\r\nFROM device_data de\r\nJOIN devices d ON de.id_collar = d.id\r\nLEFT JOIN users ei ON d.id_user = ei.id\r\nWHERE de.created_at > ($__timeTo()::timestamp - INTERVAL '7 days')\r\n AND $__timeFilter(de.created_at)\r\nORDER BY de.id_collar, de.created_at DESC;\r\n"
    },
    {
     "rawSql": "SELECT DISTINCT ON (de.id_collar)\r\n  de.id_collar, de.created_at, de.longitude, de.latitude,\r\n  d.animal_type,\r\n  ei.farm_area, ei.farm_nomos\r\nFROM device_data de\r\nJOIN devices d ON de.id_collar = d.id\r\nLEFT JOIN users ei ON d.id_user = ei.id\r\nWHERE de.created_at <= ($__timeTo()::timestamp - INTERVAL '7 days')\r\n  AND $__timeFilter(de.created_at) \r\nORDER BY de.id_collar, de.created_at DESC;\r\n"
    }
   ]
  },
  {
   "title": "Daily Active Device Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT id_collar, day, 1 as sent, messages as msg\r\nFROM device_data_daily_agg \r\nWHERE $__timeFilter(day) \r\n-- LIMIT ${DataLimit}\r\n;"
    }
   ]
  },
  {
   "title": "Daily Messages by Active Device",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 18 },
   "targets": [
    { "panelId": 35 }
   ]
  },
  { "title": "Raw Device Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Recent Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT id_collar, created_at, temperature as temp, pos_x, pos_y, pos_z \r\nFROM device_data \r\nWHERE created_at \r\n  -- BETWEEN GREATEST(($__timeFrom()::timestamp), ($__timeTo()::timestamp - INTERVAL '30 days'))\r\n  BETWEEN ($__timeTo()::timestamp - INTERVAL '30 days')\r\n  AND ($__timeTo()::timestamp)\r\n-- LIMIT ${DataLimit}\r\n;"
    }
   ]
  },
  {
   "title": "Daily Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT id_collar, day, avg_temperature as temp, avg_pos_x as pos_x, avg_pos_y as pos_y, avg_pos_z as pos_z\r\nFROM device_data_daily_agg \r\nWHERE $__timeFilter(day) \r\n-- LIMIT ${DataLimit}\r\n;"
    }
   ]
  },
  {
   "title": "Recent Accelerometer X",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
   "targets": [
    { "panelId": 26 }
   ]
  },
  {
   "title": "Daily Accelerometer X",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT id_collar, day, avg_temperature as temp, avg_pos_x as pos_x, avg_pos_y as pos_y, avg_pos_z as pos_z\r\nFROM device_data_daily_agg \r\nWHERE $__timeFilter(day) \r\n-- LIMIT ${DataLimit}\r\n;"
    }
   ]
  },
  {
   "title": "Recent Accelerometer Y",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
   "targets": [
    { "panelId": 26 }
   ]
  },
  {
   "title": "Daily Accelerometer Y",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT id_collar, day, avg_temperature as temp, avg_pos_x as pos_x, avg_pos_y as pos_y, avg_pos_z as pos_z\r\nFROM device_data_daily_agg \r\nWHERE $__timeFilter(day) \r\n-- LIMIT ${DataLimit}\r\n;"
    }
   ]
  },
  {
   "title": "Recent Accelerometer Z",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
   "targets": [
    { "panelId": 26 }
   ]
  },
  {
   "title": "Daily Accelerometer Z",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT id_collar, day, avg_temperature as temp, avg_pos_x as pos_x, avg_pos_y as pos_y, avg_pos_z as pos_z\r\nFROM device_data_daily_agg \r\nWHERE $__timeFilter(day) \r\n-- LIMIT ${DataLimit}\r\n;"
    }
   ]
  }
 ]
}